<?php

namespace AppBundle\Repository;

/**
 * AutoriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoriRepository extends \Doctrine\ORM\EntityRepository
{
}
