<?php

namespace AppBundle\Repository;

/**
 * ClanekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanekRepository extends \Doctrine\ORM\EntityRepository
{
}
