<?php

namespace AppBundle\Repository;

/**
 * RecenzentiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecenzentiRepository extends \Doctrine\ORM\EntityRepository
{
}
