<?php

namespace AppBundle\Repository;

/**
 * RevizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevizeRepository extends \Doctrine\ORM\EntityRepository
{
}
