<?php

namespace AppBundle\Repository;

/**
 * UzivatelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UzivatelRepository extends \Doctrine\ORM\EntityRepository
{
}
