# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Uzivatel:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:Uzivatel
                property: login
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: homepage
                check_path: homepage
            logout:
                path: /logout
                target: /homepage

        main:
            anonymous: ~
            # activate different ways to authenticate
            logout_on_user_change: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider

    access_control:
        #povolení přihl. formuláře pro všechny
        - { path: ^/homepage, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #povolení cesty uzivatel pro admin a user
        - { path: ^/uzivatel, roles: [ ROLE_ADMIN, ROLE_REDAKTOR, ROLE_SEFREDAKTOR, ROLE_AUTOR_REDAKTOR ] }
        #povolení cesty clanek pro admin a user
        - { path: ^/clanek, roles: [ ROLE_ADMIN, ROLE_REDAKTOR, ROLE_SEFREDAKTOR, ROLE_AUTOR_REDAKTOR ] }